### ISSUE TITLE
Crash on Windows when Open Dialog comes up

### ISSUE THREAD

**Issue by j9ac9k** [lxkain/timeview#16]
We have had a report from a user that TimeView crashes when the open file dialog comes up.  

This issue has not been duplicated by myself or @lxkain, however with searching for errors, we have seen a similar issue opened in the Spyder repository here: https://github.com/spyder-ide/spyder/issues/3903

Spyder has the same pyqt5 dependency that TimeView has, and this is likely the same issue.  Unfortunately, this issue is still open on Spyder after almost a year, and it is unlikely that a workaround/fix can be implemented at our layer, but requires a fix at the Qt layer.

Opening this issue in an effort to try duplicating the fault and implementing some kind of work-around with newer version of PyQt and so forth.

**Comment by j9ac9k** [comment]
From referencing the Spyder thread; it appears some that some Dell Backup and Recovery utilities have caused problems with Qt5 

https://pixinsight.com/forum/index.php?topic=9190.0
https://bugreports.qt.io/browse/QTBUG-41416

Dell and Alienware backup software seems to be a frequent culprit.

Autodesk Maya has a bug detailing this issue and advises their users to update their version of Dell Backup and Recover to 1.9.2.8 or later 

https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/On-some-Dell-systems-Maya-2017-crashes-when-you-use-a-file-browser.html

**Comment by j9ac9k** [comment]
Issue was resolved once Dell Backup and Recovery was removed from the system (it was unused in this case).

**Comment by lxkain** [comment]
Whoa, excellent detective work!

**Comment by j9ac9k** [comment]
yeah i got lucky w/ a search term in google, that led to the Spyder issue.
