### ISSUE TITLE
Open many files at once

### ISSUE THREAD

**Issue by rcgale** [lxkain/timeview#21]
Currently, the Track -> Open dialog only allows for one file to be opened at a time, either .wav or .lab. I would like to be able to open multiple files at once.

Even better would be if I could open a large number of files with corresponding {filename}.lab / {filename}.wav pairs, and have TimeView group them together.

**Comment by lxkain** [comment]
I believe it would be easy to support multiple files. Everything with the same stem but different suffixes would go in one and the same panel, yes? Anything more complicated can be implemented in a simple python script that calls our API, or in a future command line option mini-language.

**Comment by lxkain** [comment]
Implemented a simple version of this, that loads all selected files into the current Panel. This also works by multi-selecting files from the dataset manager, and then hitting return.
